[package]
name = "pyphonenumber"
version = "0.1.0"
authors = ["adv"]
edition = "2018"

[lib]
name = "pyphonenumber"
crate-type = ["cdylib"]

[dependencies]
phonenumber = "0.3.1+8.12.9"

[dependencies.pyo3]
version = "0.13.1"
features = ["extension-module"]
